### ISSUE TITLE
Access token can't be used for other country on first start

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#11] opened 2017-08-22 09:23 UTC
1. start app
2. secure internet
3. Australia
4. login
5. connect
6. disconnect
7. Netherlands

This all works. Then we stop the application and restart it again, we choose now Netherlands first, this triggers the OAuth dialog. But the Australian access token should be used... 

When first choosing Netherlands and then again Australia it works (within the same app session)...

It seems the app on startup doesn't know that it can use an access token from another service, only after using this service first...

**Comment by rozmansi** [comment] 2017-08-22 21:39
This works by design. It allows the user to select (perhaps different) authenticating instance on every connect.

If that is not desirable behaviour, the client can be fixed to skip the authenticating instance selection for "distributed" instance groups should user possess any reusable authentication token already.

**Comment by fkooman** [comment] 2017-08-22 21:42
Typically the user will only have an account on one of the distributed instances, i.e. the one in their own country.

**Comment by rozmansi** [comment] 2017-08-22 21:43
Ahh, just me, always trying to cover all the corner cases. Shall update the client.

**Comment by rozmansi** [comment] 2017-08-23 20:31
This issue is a subset of issue #12 and will get implicitly fixed by fixing #12.

**Closed by rozmansi** 2017-08-23 20:31 UTC
Labels: bug
