### ISSUE TITLE
openvpn not properly stopped when rebooting system

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#171] opened 2021-08-02 07:43 UTC
It seems the OpenVPN process is not properly stopped when the system is rebooted. When the OpenVPN process is stopped the server is usually informed through the `--explicit-exit-notify`. This does not seem to happen when rebooting the system. When quitting the application yourself, it *does* happen.

I don't know whether this is easy to fix, whether it is worth fixing, or whether there is even an option to do this through a hook or something, but somehow it feels more "clean" to properly stop the VPN before rebooting...

**Comment by rozmansi** [comment] 2021-08-23 09:37
There is a general guideline to make shutdowns as fast as possible. Windows get WM_ENDSESSION message which allows them to take "the fast way out".

Will explore the source code to see, how it handles OpenVPN tunnel and change it from "fast exit" to a graceful one.

**Comment by rozmansi** [comment] 2021-08-31 12:34
> I don't know whether this is easy to fix, whether it is worth fixing, or whether there is even an option to do this through a hook or something, but somehow it feels more "clean" to properly stop the VPN before rebooting...

This one is indeed hard to fix. I have set up a VPC to run eduVPN client with debugger attached to try to understand what is happening when user signs out.

The `openvpn.exe` does use `SetConsoleCtrlHandler()` to listen for Ctrl+C and Ctrl+Break events (but not shutdown). However, according to the `--verb 11`, the handler is not even called on sign out. The `openvpn.exe` dies the same moment without writing anything to the log file. It appears that either the interactive service or Windows itself kills the `openvpn.exe`. The `openvpn.exe` doesn't have a console, since the interactive service runs it with `CREATE_NO_WINDOW`. Hence, its console control handler setting is probably futile.

So, even when I upgraded the eduVPN client to do a graceful OpenVPN session disconnection on user sign out, the OpenVPN session is just killed before it even gets a chance to receive our request to disconnect.

In order to fix this, OpenVPN should be upgraded first.

**Comment by fkooman** [comment] 2021-08-31 19:15
I guess I was thinking too simple. In Windows, apps can't (temporary) prevent shutdown? e.g. to save the open files or something? If that is not possible we are done indeed. If it *is* then this time window can be used to disconnect the VPN, just like is done when the user manually disconnects the VPN during normal use...

It seems strange that Windows does `kill -9` on random processes when the eduVPN app still wants to close itself?

**Comment by rozmansi** [comment] 2021-09-01 18:42
As I see it, Windows iterates over all the processes. The processes with console are sent `CTRL_LOGOFF_EVENT` or `CTRL_SHUTDOWN_EVENT`; the processes with windows (message loop) are sent `WM_ENDSESSION`; the processes without any of those are killed. Unfortunately, an `openvpn.exe` process started by the interactive service has no console or window, therefore, it's just killed.

In my observations, `openvpn.exe` disappears so fast, the eduVPN Client request to stop the tunnel gracefully comes too late.

Maybe, we could amend the interactive service to spawn `openvpn.exe` with a console, and upgrade the latter to respond to the `CTRL_LOGOFF_EVENT` or `CTRL_SHUTDOWN_EVENT` in the same manner as it responds to `CTRL_C_EVENT` and `CTRL_BREAK_EVENT`.

**Comment by rozmansi** [comment] 2021-09-02 13:43
> Maybe, we could amend the interactive service to spawn `openvpn.exe` with a console, and upgrade the latter to respond to the `CTRL_LOGOFF_EVENT` or `CTRL_SHUTDOWN_EVENT` in the same manner as it responds to `CTRL_C_EVENT` and `CTRL_BREAK_EVENT`.

Tried this today, but it doesn't stop gracefully. What's worse, it pops up an `openvpn.exe` console window on the user desktop. :(

**Comment by fkooman** [comment] 2021-09-02 14:03
Ouch, sorry to hear that! It doesn't look good... But maybe that is just the way it is then... the iOS/macOS apps also don't notify the server they are leaving...

**Comment by fkooman** [comment] 2021-09-23 18:35
This can probably be fixed with APIv3! 

The reason why is that the *application* sends an API call "/disconnect" to the server which will remove the certificate on the server and disconnect the client (forcibly if the client doesn't leave by itself). So as long as the application can hold up the shutdown of Windows until the HTTP "/disconnect" API call was sent out we'll be good. 

This is also *very* important for WireGuard, this way the server can remove the peer when the client disconnects and release the VPN IP address.

**Comment by rozmansi** [comment] 2021-09-23 19:01
With WireGuard, I was actually thinking about the same workflow as the official WireGuard client does:

If the client is connected when user shuts down the computer, the tunnel service stays in place. Meaning that the tunnel comes back up on boot automatically. This is very positive in terms of Group Policy processing: the laptop can and will install GPO-published software on boot, the logon will verify user credentials against AD server rather than relying on cached one etc. This is also positive, when roaming and secure internet from is desired on boot.

After all, the user did not want to disconnect the tunnel. The user just wanted to reboot or shutdown the computer.

Maybe on shutdown, we could bring the tunnel down and do the /disconnect. And on boot (should the session not be expired yet), have the tunnel tracking service do the /connect and bring the tunnel up?

**Comment by fkooman** [comment] 2021-09-23 19:27
Right. I was actually thinking of an approach that would work with this, but also with OpenVPN. To make a distinction between *system* VPN and *user* VPN. 

If you are doing GPO stuff, then we might as well give the eduVPN server an "admin API" for bulk retrieval of configuration files that you can distribute to your clients. This can work for both OpenVPN and WG, then there is no need for user interaction at all! 

For user VPN we'd use the eduVPN client, for system VPN we use the WireGuard / OpenVPN Community client...

**Comment by rozmansi** [comment] 2022-02-01 10:10
> For user VPN we'd use the eduVPN client, for system VPN we use the WireGuard / OpenVPN Community client...

Would work. WireGuard is true _system_ VPN by design (people have trouble comprehending this idea). OpenVPN Community client has a .NET service to auto-start tunnels on boot. Thou it is not maintained. A couple of years ago, we discussed this on OpenVPN mailing list and the true way forward would be to rewrite the .NET service (possibly in C) and make a nonpriviledged service that uses the interactive service to run tunnels.

**Comment by rozmansi** [comment] 2022-02-01 10:12
As user sign off/shutdown notification of client termination has been solved in 16b509774ce10574a357b73588111f50f3bfc526 now, I am closing this issue.

**Closed by rozmansi** 2022-02-01 10:12 UTC
Labels: enhancement
