### ISSUE TITLE
OpenVPN reported fatal error. Failed to open wintun adapter

### ISSUE THREAD

**Issue by TrueBeastEmperor** [Amebis/eduVPN#251] opened 2024-10-31 19:22 UTC
OpenVPN reported fatal error.
Failed to open wintun adapter: {0a7dae7c-68a5-599c-97da-5378d77f1bb3}

Same stuff no matter what I do.

**Comment by rozmansi** [comment] 2024-11-13 09:30
I managed to reproduce your issue.

Started my test PC, and at first attempt eduVPN client connected using OpenVPN and Wintun normally. Went on writing detailed instructions for you, how you can troubleshoot the situation. Returned to my test PC to make some more screenshots, while hitting the same issue as you. Repeatedly. Noticed the Windows were installing KB5001716, KB5046542 and KB5046613 updates in the background. Until updates were installed all attempts to create a Wintun adapter by eduVPN client were failing. After updates were installed and computer restarted, the eduVPN client, OpenVPN and Wintun adapter were working normally again.

Can you confirm, it is working for you too now, please?

**Comment by rozmansi** [comment] 2024-11-19 07:52
OK, then...

1. Please consult the OpenVPN logs found in `C:\Program Files\eduVPN\OpenVPN\config`. There should be some fatal errors like "Creating Wintun adapter failed using service" in there and some status numbers that could shed me some light what went wrong. Can you locate those logs and [e-mail them to me](mailto:simon.rozman@amebis.si) for analysis, please?

2. Quit the eduVPN client, or at least make sure it is disconnected from a VPN, and run Device Manager as Administrator. Expand the Network Adapters node. There should be no Wintun adapters there.

   When eduVPN Client is connected:
   ![image](https://github.com/user-attachments/assets/8731371b-4fdb-4dce-bf91-04411c650b3a)

   When eduVPN Client is not connected:
   ![image](https://github.com/user-attachments/assets/2058cf0f-46a8-40e8-a8c3-e32853226cdb)

   If there are any Wintun adapters, delete them. When you are deleting the last one, you may choose to uninstall the driver. It will be reinstalled automatically on the next connection attempt.

I am really curious to get your feedback, and thank you for your patience.

**Comment by rozmansi** [comment] 2024-11-29 13:02
Thank you for your feedback.

I suspect we are suffering the same issue as https://github.com/OpenVPN/ovpn-dco-win/issues/38. Some posts there suggest installing the software elevated (Run as Administrator). Installing using our EXE installer already does that, so it shouldn't make any difference in your case.

I have also upgraded future versions of eduVPN client to include the reason why _CreateFile failed on wintun device_, like the stock OpenVPN did. However, I am suspecting you will just get the same _Access Denied (code=5)_ as people do with ovpn-dco-win.

Given others have already tried to uninstall the product, remove TUN devices, uninstall the driver to no avail, I have no idea how to fix this. Something seems to be different with your Windows. Maybe some configuration change, security settings, or some other security/anti-virus/sandboxing software?

Fixing this should involve a deep surgery in OpenVPN to move adapter handling from `openvpn.exe` process to `openvpnserv.exe`.

**Comment by rozmansi** [comment] 2024-12-03 08:28
We are moving to https://codeberg.org/eduVPN/windows/issues/251
Sorry for the inconvenience.

**Closed by rozmansi** 2024-12-03 08:28 UTC
Labels: bug
