### ISSUE TITLE
With preset 'InstituteAccessServers' in registry eduVPN (3.3) won't start (+ Allow user modification)

### ISSUE THREAD

**Issue by Lukas-UAUX** [Amebis/eduVPN#210] opened 2022-09-02 13:20 UTC
Hi, so I tested to configure eduVPN like described here https://github.com/Amebis/eduVPN/blob/master/doc/Customization.md - I added only `InstituteAccessServers` with one URI. 

But afterwards it won't launch anymore. I deleted the folders in AppData, but that won't help... 

Trying the first time, it just does nothing - trying it a second time only a black window shows that does nothing. 

(I installed version 3.3 from the MSI)

Also when you're at it could you add a way of still allowing the user to still add new servers even if we preset one (maybe with an additional 'locked' parameter that can be disabled)? We do intend to preset ours on managed devices but we don not want to lock it. Why? Because discovery has multiple similar search results - and yes that is too complicated for some users, but we also have advanced users who need to connect to different institutions sometimes.

**Comment by rozmansi** [comment] 2022-09-05 17:49
I am unable to reproduce this issue. Have released 3.3.1 today with some additional trace logging. Maybe you can install it and edit `C:\Program Files\eduVPN\Core\eduVPN.Client.exe.config` scroll to the end and uncomment the logging to `C:\output.log`. Hopefully, I could get some useful clues from your `C:\output.log` how far your client gets and when it breaks.

> Also when you're at it could you add a way of still allowing the user to still add new servers even if we preset one (maybe with an additional 'locked' parameter that can be disabled)? We do intend to preset ours on managed devices but we don not want to lock it. Why? Because discovery has multiple similar search results - and yes that is too complicated for some users, but we also have advanced users who need to connect to different institutions sometimes.

When you preconfigure the list of _Institute Access_ servers, user may still use the _Secure Internet_ or add own servers. Advanced users can click the `+` button and enter hostname* of other institution's server to connect to it. GUI will show those manually entered servers on a separate list, but will allow user to connect to them the same. So, technically this is already doable.
Nevertheless, I shall discuss your suggestion with the rest of the eduVPN team and maybe allow additional _Institute Access_ servers next to the preconfigured one(s).

\* No leading "https://" or trailing path "/". Just "hostname.domain.org".

**Comment by rozmansi** [comment] 2022-09-07 07:31
> Nevertheless, I shall discuss your suggestion with the rest of the eduVPN team and maybe allow additional Institute Access servers next to the preconfigured one(s).

@Lukas-UAUX, your suggestion was implemented and will be included in the next release.

**Closed** 2022-10-18 11:54 UTC
Labels: bug, enhancement

**Comment by rozmansi** [comment] 2022-10-19 07:53
I have released [3.3.2](https://github.com/Amebis/eduVPN/releases/tag/3.3.2) which now allows additional Institute Access servers next to the preconfigured one(s).

**Comment by Lukas-UAUX** [comment] 2022-11-18 16:10
Btw. I found the issue why my client was not starting - i omitted the https:// and trailing slash (as I would have typed it into the search/url filed in the client). That you added the example in the documentation helped ;-)

As far as I can tell the changed feature works as expected, but I will wait until it is merged into a stable build. Thank you!
