### ISSUE TITLE
Semaphore timeout

### ISSUE THREAD

**Issue by tobias-irlinger** [Amebis/eduVPN#200] opened 2022-06-27 15:31 UTC
Hi,

ich habe folgenden Error in Version: 3.1.2:

Sorry für die deutsche Fehlermeldung.

System.AggregateException: Interaktiver Dienst gescheitert. ---> System.AggregateException: Die Verbindung zum interaktiven Dienstopenvpn$eduVPN\service ist fehlgeschlagen. Vergewissern Sie sich bitte, dass der Dienst gestartet ist. ---> System.IO.IOException: Das Zeitlimit für die Semaphore wurde erreicht.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   bei eduOpenVPN.InteractiveService.Session.Connect(String pipeName, String workingFolder, String[] arguments, String stdin, Int32 timeout, CancellationToken ct)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei eduOpenVPN.InteractiveService.Session.Connect(String pipeName, String workingFolder, String[] arguments, String stdin, Int32 timeout, CancellationToken ct)
   bei eduVPN.ViewModels.VPN.OpenVPNSession.Run()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei eduVPN.ViewModels.Pages.ConnectionPage.<>c__DisplayClass28_2.<get_StartSession>b__9()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Interne Ausnahme #0) System.AggregateException: Die Verbindung zum interaktiven Dienstopenvpn$eduVPN\service ist fehlgeschlagen. Vergewissern Sie sich bitte, dass der Dienst gestartet ist. ---> System.IO.IOException: Das Zeitlimit für die Semaphore wurde erreicht.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   bei eduOpenVPN.InteractiveService.Session.Connect(String pipeName, String workingFolder, String[] arguments, String stdin, Int32 timeout, CancellationToken ct)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei eduOpenVPN.InteractiveService.Session.Connect(String pipeName, String workingFolder, String[] arguments, String stdin, Int32 timeout, CancellationToken ct)
   bei eduVPN.ViewModels.VPN.OpenVPNSession.Run()
---> (Interne Ausnahme #0) System.IO.IOException: Das Zeitlimit für die Semaphore wurde erreicht.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   bei eduOpenVPN.InteractiveService.Session.Connect(String pipeName, String workingFolder, String[] arguments, String stdin, Int32 timeout, CancellationToken ct)<---
<---

![image](https://user-images.githubusercontent.com/105930543/175977032-588f9932-fa57-44de-a61f-cc9c9a25affa.png)

**Comment by hm-tobias** [comment] 2022-06-27 16:58
Additional information: The error occurred after waking up from power-saving mode. After a reboot, the VPN connection could be established again.

**Comment by rozmansi** [comment] 2022-06-28 10:59
Are you really sure, this is a version 3.1.2? This specific error appeared in 3.0 and was fixed in 3.0.1.

**Comment by rozmansi** [comment] 2022-06-28 11:00
#196

**Comment by hm-tobias** [comment] 2022-06-28 11:00
Yes im am sure. Sorry

**Comment by hm-tobias** [comment] 2022-06-28 12:31
I will test the behaviour again when I change the network again. (Wifi)

**Comment by hm-tobias** [comment] 2022-06-28 13:36
Attached is the log as XML. These are sorted according to the following timestamp: 
2022-06-27T13: Office VPN works
2022-06-27T16: Home VPN does not work
2022-06-27T18:50: Home VPN works after reboot

[eduvpn_xml.txt](https://github.com/Amebis/eduVPN/files/9001367/eduvpn_xml.txt)

**Comment by hm-tobias** [comment] 2022-06-29 07:51
Quick info: The wifi change did not cause any problems today. EduVPN automatically reconnected as desired, from an energy-saving mode. 
EduVPN version 3.1.4

**Comment by rozmansi** [comment] 2022-06-29 11:38
> Attached is the log as XML. These are sorted according to the following timestamp:

Weird... After resume (15:21:27) OpenVPN just cleaned up the connection then nothing! At 16:56:25 you probably initiated a VPN connection manually. The second resume (18:50:28) works as intended. Your log just confirms what you are describing. Unfortunately, it doesn't answer me, what went wrong the Interactive Service got into a weird state where it refused to accept requests preventing eduVPN to reconnect.

> Quick info: The wifi change did not cause any problems today. EduVPN automatically reconnected as desired, from an energy-saving mode.
> EduVPN version 3.1.4

That's good to hear.
I'm still under impression that openvpnserv.exe binary didn't upgrade and remained 2.5.6.5 (2.5.6-20220509) until after a reboot.

Keeping this issue open.

**Comment by hm-tobias** [comment] 2022-06-29 11:52
I will get back to you as soon as the problem occurs again.

**Closed as completed** 2022-06-30 14:40 UTC
Labels: bug
