### ISSUE TITLE
Terminate connection with right mouse click in govVPN Windows client

### ISSUE THREAD

**Issue by govroam** [Amebis/eduVPN#240] opened 2024-04-05 11:53 UTC
just like MacOS, as discussed with Rogier

**Comment by efef** [comment] 2024-04-05 20:04
<img width="335" alt="Screenshot 2024-04-05 at 22 04 25" src="https://github.com/Amebis/eduVPN/assets/3393474/9ff0314a-f62b-41e2-8e01-7999b9f2d7eb">
example from macOS

**Comment by efef** [comment] 2024-04-05 20:08
Idea is to be able to start/stop via systray, for macOS you can even switch between profiles

on macOS when I click on the active profile, the VPN disconnects that profile

Would be nice to have on Windows too

**Comment by rozmansi** [comment] 2024-04-06 02:34
Thanks for your suggestion. This is a duplicate of #111. I reopened it and added it on 4.x TODO.

**Closed by rozmansi** 2024-04-06 02:34 UTC
Labels: duplicate

**Comment by govroam** [comment] 2024-04-10 07:14
great and fast work! THanks
